[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm install --legacy-peer-deps && npx prisma generate && npm run build"

[deploy]
startCommand = "cd server && npm run start:prod"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
