import { Injectable } from '@nestjs/common';

export type AgentMode = 'COPILOT' | 'AUTOPILOT';
export type AgentPermissionState = 'READ_ONLY' | 'APPROVAL_REQUIRED' | 'AUTOPILOT_SAFE' | 'FORBIDDEN' | 'SYSTEM_ONLY';

export interface AgentPolicyContext { salonId: string; userId: string; role: string; mode: AgentMode; correlationId: string; agentRunId: string; }
export interface AgentPolicyRequest { toolName: string; context: AgentPolicyContext; resource?: { salonId?: string }; }
export interface AgentPolicyDecision { allowed: boolean; state: AgentPermissionState; code: string; reason: string; }

const READ_ONLY_TOOLS = new Set(['get_customer','search_customers','get_customer_history','get_appointments','get_available_slots','get_services','get_staff','get_reviews','prepare_customer_message']);
const APPROVAL_TOOLS = new Set(['create_booking','cancel_booking','send_customer_message']);

@Injectable()
export class AgentPolicyEngine {
  async evaluate(request: AgentPolicyRequest): Promise<AgentPolicyDecision> {
    if (request.resource?.salonId && request.resource.salonId !== request.context.salonId) return { allowed:false, state:'FORBIDDEN', code:'TENANT_ACCESS_DENIED', reason:'The requested resource belongs to another salon.' };
    if (request.toolName === 'record_agent_decision') return { allowed:false, state:'SYSTEM_ONLY', code:'SYSTEM_ONLY', reason:'Agent decision records are generated by the server.' };
    if (READ_ONLY_TOOLS.has(request.toolName)) return { allowed:true, state:'READ_ONLY', code:'ALLOWED', reason:'Read-only tool permitted for the authenticated salon.' };
    if (APPROVAL_TOOLS.has(request.toolName)) {
      if (request.context.mode === 'COPILOT') return { allowed:false, state:'APPROVAL_REQUIRED', code:'APPROVAL_REQUIRED', reason:'This action requires human approval in Copilot mode.' };
      return { allowed:true, state:'AUTOPILOT_SAFE', code:'POLICY_CHECK_REQUIRED', reason:'Autopilot execution requires action-specific policy predicates.' };
    }
    return { allowed:false, state:'FORBIDDEN', code:'POLICY_DENIED', reason:'The requested tool is not part of the approved Agent capability set.' };
  }
}
